/// enum all the countries that have Alpha-2 country code as described in the ISO 3166 international standard
enum WeatherCountryCodes {
  aghanistan,
  alandIslands,
  albania,
  algeria,
  americanSamoa,
  andorra,
  angola,
  anguilla,
  antarctica,
  antiguaAndBarbuda,
  argentina,
  armenia,
  aruba,
  australia,
  austria,
  azerbaijan,
  bahamas,
  bahrain,
  bangladesh,
  barbados,
  belarus,
  belgium,
  belize,
  benin,
  bermuda,
  bhutan,
  bolivia,
  bonbeSintEustatiusAndSaba,
  bosniandHerzegovina,
  botswana,
  bouvetIsland,
  brazil,
  britishIndianOceanTerritory,
  bruneiDarussalam,
  bulgaria,
  burkinaFaso,
  burundi,
  caboVerde,
  cambodia,
  cameroon,
  canada,
  caymanIslands,
  centralAfricanRepublic,
  chad,
  chile,
  china,
  christmasIsland,
  cocosIslands,
  colombia,
  comoros,
  congo,
  congoDemocraticRepublic,
  cookIslands,
  costaRica,
  cotedIvoire,
  croatia,
  cuba,
  curacao,
  cyprus,
  czechia,
  denmark,
  djibouti,
  dominica,
  dominicanRepublic,
  ecuador,
  egypt,
  elSalvador,
  equatorialGuinea,
  eritrea,
  estonia,
  eswatini,
  ethiopia,
  falklandIslands,
  faroeIslands,
  fiji,
  finland,
  france,
  frenchGuiana,
  frenchPolynesia,
  frenchSouthernTerritories,
  gabon,
  gambia,
  georgia,
  germany,
  ghana,
  gibraltar,
  greece,
  greenland,
  grenada,
  guadeloupe,
  guam,
  guatemala,
  guernsey,
  guinea,
  guineaBissau,
  guyana,
  haiti,
  heardIslandAndMcDonaldIslands,
  holySee,
  honduras,
  hongKong,
  hungary,
  iceland,
  india,
  indonesia,
  iran,
  iraq,
  ireland,
  isleOfMan,
  israel,
  italy,
  jamaica,
  japan,
  jersey,
  jordan,
  kazakhstan,
  kenya,
  kiribati,
  koreaNorth,
  koreaSouth,
  kuwait,
  kyrgyzstan,
  laos,
  latvia,
  lebanon,
  lesotho,
  liberia,
  libya,
  liechtenstein,
  lithuania,
  luxembourg,
  macao,
  madagascar,
  malawi,
  malaysia,
  maldives,
  mali,
  malta,
  marshallIslands,
  martinique,
  mauritania,
  mauritius,
  mayotte,
  mexico,
  micronesia,
  moldova,
  monaco,
  mongolia,
  montenegro,
  montserrat,
  morocco,
  mozambique,
  myanmar,
  namibia,
  nauru,
  nepal,
  netherlands,
  newCaledonia,
  newZealand,
  nicaragua,
  niger,
  nigeria,
  niue,
  norfolkIsland,
  northMacedonia,
  northernMarianaIslands,
  norway,
  oman,
  pakistan,
  palau,
  palestine,
  panama,
  papuaNewGuinea,
  paraguay,
  peru,
  philippines,
  pitcairn,
  poland,
  portugal,
  puertoRico,
  qatar,
  reunion,
  romania,
  russianFederation,
  rwanda,
  saintBarthelemy,
  saintHelenaAscensionAndTristanDaCunha,
  saintKittsAndNevis,
  saintLucia,
  saintMartin,
  saintPierreAndMiquelon,
  saintVincentAndTheGrenadines,
  samoa,
  sanMarino,
  saoTomeAndPrincipe,
  saudiArabia,
  senegal,
  serbia,
  seychelles,
  sierraLeone,
  singapore,
  sintMaarten,
  slovakia,
  slovenia,
  solomonIslands,
  somalia,
  southAfrica,
  southGeorgiaAndTheSouthSandwichIslands,
  southSudan,
  spain,
  sriLanka,
  sudan,
  suriname,
  svalbardAndJanMayen,
  sweden,
  switzerland,
  syrianArabRepublic,
  taiwan,
  tajikistan,
  tanzania,
  thailand,
  timorLeste,
  togo,
  tokelau,
  tonga,
  trinidadAndTobago,
  tunisia,
  turkiye,
  turkmenistan,
  turksAndCaicosIslands,
  tuvalu,
  uganda,
  ukraine,
  unitedArabEmirates,
  unitedKingdomofGreatBritainandNorthernIreland,
  unitedStatesMinorOutlyingIslands,
  unitedStatesOfAmerica,
  uruguay,
  uzbekistan,
  vanuatu,
  venezuela,
  vietnam,
  virginIslandsBritish,
  virginIslandsUS,
  wallisAndFutuna,
  westernSahara,
  yemen,
  zambia,
  zimbabwe,
}

/// Maps enum [WeatherCountryCodes] to their String Alpha-2 code
Map<WeatherCountryCodes, String> weatherCountryCodesString = {
  WeatherCountryCodes.aghanistan: 'AF',
  WeatherCountryCodes.alandIslands: 'AX',
  WeatherCountryCodes.albania: 'AL',
  WeatherCountryCodes.algeria: 'DZ',
  WeatherCountryCodes.americanSamoa: 'AS',
  WeatherCountryCodes.andorra: 'AD',
  WeatherCountryCodes.angola: 'AO',
  WeatherCountryCodes.anguilla: 'AI',
  WeatherCountryCodes.antarctica: 'AQ',
  WeatherCountryCodes.antiguaAndBarbuda: 'AG',
  WeatherCountryCodes.argentina: 'AR',
  WeatherCountryCodes.armenia: 'AM',
  WeatherCountryCodes.aruba: 'AW',
  WeatherCountryCodes.australia: 'AU',
  WeatherCountryCodes.austria: 'AT',
  WeatherCountryCodes.azerbaijan: 'AZ',
  WeatherCountryCodes.bahamas: 'BS',
  WeatherCountryCodes.bahrain: 'BH',
  WeatherCountryCodes.bangladesh: 'BD',
  WeatherCountryCodes.barbados: 'BB',
  WeatherCountryCodes.belarus: 'BY',
  WeatherCountryCodes.belgium: 'BE',
  WeatherCountryCodes.belize: 'BZ',
  WeatherCountryCodes.benin: 'BJ',
  WeatherCountryCodes.bermuda: 'BM',
  WeatherCountryCodes.bhutan: 'BT',
  WeatherCountryCodes.bolivia: 'BO',
  WeatherCountryCodes.bonbeSintEustatiusAndSaba: 'BQ',
  WeatherCountryCodes.bosniandHerzegovina: 'BA',
  WeatherCountryCodes.botswana: 'BW',
  WeatherCountryCodes.bouvetIsland: 'BV',
  WeatherCountryCodes.brazil: 'BR',
  WeatherCountryCodes.britishIndianOceanTerritory: 'IO',
  WeatherCountryCodes.bruneiDarussalam: 'BN',
  WeatherCountryCodes.bulgaria: 'BG',
  WeatherCountryCodes.burkinaFaso: 'BF',
  WeatherCountryCodes.burundi: 'BI',
  WeatherCountryCodes.caboVerde: 'CV',
  WeatherCountryCodes.cambodia: 'KH',
  WeatherCountryCodes.cameroon: 'CM',
  WeatherCountryCodes.canada: 'CA',
  WeatherCountryCodes.caymanIslands: 'KY',
  WeatherCountryCodes.centralAfricanRepublic: 'CF',
  WeatherCountryCodes.chad: 'TD',
  WeatherCountryCodes.chile: 'CL',
  WeatherCountryCodes.china: 'CN',
  WeatherCountryCodes.christmasIsland: 'CZ',
  WeatherCountryCodes.cocosIslands: 'CC',
  WeatherCountryCodes.colombia: 'CO',
  WeatherCountryCodes.comoros: 'KM',
  WeatherCountryCodes.congo: 'CG',
  WeatherCountryCodes.congoDemocraticRepublic: 'CD',
  WeatherCountryCodes.cookIslands: 'CK',
  WeatherCountryCodes.costaRica: 'CR',
  WeatherCountryCodes.cotedIvoire: 'CI',
  WeatherCountryCodes.croatia: 'HR',
  WeatherCountryCodes.cuba: 'CU',
  WeatherCountryCodes.curacao: 'CW',
  WeatherCountryCodes.cyprus: 'CY',
  WeatherCountryCodes.czechia: 'CZ',
  WeatherCountryCodes.denmark: 'DK',
  WeatherCountryCodes.djibouti: 'DJ',
  WeatherCountryCodes.dominica: 'DM',
  WeatherCountryCodes.dominicanRepublic: 'DO',
  WeatherCountryCodes.ecuador: 'EC',
  WeatherCountryCodes.egypt: 'EG',
  WeatherCountryCodes.elSalvador: 'SV',
  WeatherCountryCodes.equatorialGuinea: 'GQ',
  WeatherCountryCodes.eritrea: 'ER',
  WeatherCountryCodes.estonia: 'EE',
  WeatherCountryCodes.eswatini: 'SZ',
  WeatherCountryCodes.ethiopia: 'ET',
  WeatherCountryCodes.falklandIslands: 'FK',
  WeatherCountryCodes.faroeIslands: 'FO',
  WeatherCountryCodes.fiji: 'FJ',
  WeatherCountryCodes.finland: 'FI',
  WeatherCountryCodes.france: 'FR',
  WeatherCountryCodes.frenchGuiana: 'GF',
  WeatherCountryCodes.frenchPolynesia: 'PF',
  WeatherCountryCodes.frenchSouthernTerritories: 'TF',
  WeatherCountryCodes.gabon: 'GA',
  WeatherCountryCodes.gambia: 'GM',
  WeatherCountryCodes.georgia: 'GE',
  WeatherCountryCodes.germany: 'DE',
  WeatherCountryCodes.ghana: 'GH',
  WeatherCountryCodes.gibraltar: 'GI',
  WeatherCountryCodes.greece: 'GR',
  WeatherCountryCodes.greenland: 'GL',
  WeatherCountryCodes.grenada: 'GD',
  WeatherCountryCodes.guadeloupe: 'GP',
  WeatherCountryCodes.guam: 'GU',
  WeatherCountryCodes.guatemala: 'GT',
  WeatherCountryCodes.guernsey: 'GG',
  WeatherCountryCodes.guinea: 'GN',
  WeatherCountryCodes.guineaBissau: 'GW',
  WeatherCountryCodes.guyana: 'GY',
  WeatherCountryCodes.haiti: 'HT',
  WeatherCountryCodes.heardIslandAndMcDonaldIslands: 'HM',
  WeatherCountryCodes.holySee: 'VA',
  WeatherCountryCodes.honduras: 'HN',
  WeatherCountryCodes.hongKong: 'HK',
  WeatherCountryCodes.hungary: 'HU',
  WeatherCountryCodes.iceland: 'IS',
  WeatherCountryCodes.india: 'IN',
  WeatherCountryCodes.indonesia: 'ID',
  WeatherCountryCodes.iran: 'IR',
  WeatherCountryCodes.iraq: 'IQ',
  WeatherCountryCodes.ireland: 'IE',
  WeatherCountryCodes.isleOfMan: 'IM',
  WeatherCountryCodes.israel: 'IL',
  WeatherCountryCodes.italy: 'IT',
  WeatherCountryCodes.jamaica: 'JM',
  WeatherCountryCodes.japan: 'JP',
  WeatherCountryCodes.jersey: 'JE',
  WeatherCountryCodes.jordan: 'JO',
  WeatherCountryCodes.kazakhstan: 'KZ',
  WeatherCountryCodes.kenya: 'KE',
  WeatherCountryCodes.kiribati: 'KI',
  WeatherCountryCodes.koreaNorth: 'KP',
  WeatherCountryCodes.koreaSouth: 'KR',
  WeatherCountryCodes.kuwait: 'KW',
  WeatherCountryCodes.kyrgyzstan: 'KG',
  WeatherCountryCodes.laos: 'LA',
  WeatherCountryCodes.latvia: 'LV',
  WeatherCountryCodes.lebanon: 'LB',
  WeatherCountryCodes.lesotho: 'LS',
  WeatherCountryCodes.liberia: 'LR',
  WeatherCountryCodes.libya: 'LY',
  WeatherCountryCodes.liechtenstein: 'LI',
  WeatherCountryCodes.lithuania: 'LT',
  WeatherCountryCodes.luxembourg: 'LU',
  WeatherCountryCodes.macao: 'MO',
  WeatherCountryCodes.madagascar: 'MG',
  WeatherCountryCodes.malawi: 'MW',
  WeatherCountryCodes.malaysia: 'MY',
  WeatherCountryCodes.maldives: 'MV',
  WeatherCountryCodes.mali: 'ML',
  WeatherCountryCodes.malta: 'MT',
  WeatherCountryCodes.marshallIslands: 'MH',
  WeatherCountryCodes.martinique: 'MQ',
  WeatherCountryCodes.mauritania: 'MR',
  WeatherCountryCodes.mauritius: 'MU',
  WeatherCountryCodes.mayotte: 'YT',
  WeatherCountryCodes.mexico: 'MX',
  WeatherCountryCodes.micronesia: 'FM',
  WeatherCountryCodes.moldova: 'MD',
  WeatherCountryCodes.monaco: 'MC',
  WeatherCountryCodes.mongolia: 'MN',
  WeatherCountryCodes.montenegro: 'ME',
  WeatherCountryCodes.montserrat: 'MS',
  WeatherCountryCodes.morocco: 'MA',
  WeatherCountryCodes.mozambique: 'MZ',
  WeatherCountryCodes.myanmar: 'MM',
  WeatherCountryCodes.namibia: 'NA',
  WeatherCountryCodes.nauru: 'NR',
  WeatherCountryCodes.nepal: 'NP',
  WeatherCountryCodes.netherlands: 'NL',
  WeatherCountryCodes.newCaledonia: 'NC',
  WeatherCountryCodes.newZealand: 'NZ',
  WeatherCountryCodes.nicaragua: 'NI',
  WeatherCountryCodes.niger: 'NE',
  WeatherCountryCodes.nigeria: 'NG',
  WeatherCountryCodes.niue: 'NU',
  WeatherCountryCodes.norfolkIsland: 'NF',
  WeatherCountryCodes.northMacedonia: 'MK',
  WeatherCountryCodes.northernMarianaIslands: 'MP',
  WeatherCountryCodes.norway: 'NO',
  WeatherCountryCodes.oman: 'OM',
  WeatherCountryCodes.pakistan: 'PK',
  WeatherCountryCodes.palau: 'PW',
  WeatherCountryCodes.palestine: 'PS',
  WeatherCountryCodes.panama: 'PA',
  WeatherCountryCodes.papuaNewGuinea: 'PG',
  WeatherCountryCodes.paraguay: 'PY',
  WeatherCountryCodes.peru: 'PE',
  WeatherCountryCodes.philippines: 'PH',
  WeatherCountryCodes.pitcairn: 'PN',
  WeatherCountryCodes.poland: 'PL',
  WeatherCountryCodes.portugal: 'PT',
  WeatherCountryCodes.puertoRico: 'PR',
  WeatherCountryCodes.qatar: 'QA',
  WeatherCountryCodes.reunion: 'RE',
  WeatherCountryCodes.romania: 'RO',
  WeatherCountryCodes.russianFederation: 'RU',
  WeatherCountryCodes.rwanda: 'RW',
  WeatherCountryCodes.saintBarthelemy: 'BL',
  WeatherCountryCodes.saintHelenaAscensionAndTristanDaCunha: 'SH',
  WeatherCountryCodes.saintKittsAndNevis: 'KN',
  WeatherCountryCodes.saintLucia: 'LC',
  WeatherCountryCodes.saintMartin: 'MF',
  WeatherCountryCodes.saintPierreAndMiquelon: 'PM',
  WeatherCountryCodes.saintVincentAndTheGrenadines: 'VC',
  WeatherCountryCodes.samoa: 'WS',
  WeatherCountryCodes.sanMarino: 'SM',
  WeatherCountryCodes.saoTomeAndPrincipe: 'ST',
  WeatherCountryCodes.saudiArabia: 'SA',
  WeatherCountryCodes.senegal: 'SN',
  WeatherCountryCodes.serbia: 'RS',
  WeatherCountryCodes.seychelles: 'SC',
  WeatherCountryCodes.sierraLeone: 'SL',
  WeatherCountryCodes.singapore: 'SG',
  WeatherCountryCodes.sintMaarten: 'SX',
  WeatherCountryCodes.slovakia: 'SK',
  WeatherCountryCodes.slovenia: 'SI',
  WeatherCountryCodes.solomonIslands: 'SB',
  WeatherCountryCodes.somalia: 'SO',
  WeatherCountryCodes.southAfrica: 'ZA',
  WeatherCountryCodes.southGeorgiaAndTheSouthSandwichIslands: 'GS',
  WeatherCountryCodes.southSudan: 'SS',
  WeatherCountryCodes.spain: 'ES',
  WeatherCountryCodes.sriLanka: 'LK',
  WeatherCountryCodes.sudan: 'SD',
  WeatherCountryCodes.suriname: 'SR',
  WeatherCountryCodes.svalbardAndJanMayen: 'SJ',
  WeatherCountryCodes.sweden: 'SE',
  WeatherCountryCodes.switzerland: 'CH',
  WeatherCountryCodes.syrianArabRepublic: 'SY',
  WeatherCountryCodes.taiwan: 'TW',
  WeatherCountryCodes.tajikistan: 'TJ',
  WeatherCountryCodes.tanzania: 'TZ',
  WeatherCountryCodes.thailand: 'TH',
  WeatherCountryCodes.timorLeste: 'TL',
  WeatherCountryCodes.togo: 'TG',
  WeatherCountryCodes.tokelau: 'TK',
  WeatherCountryCodes.tonga: 'TO',
  WeatherCountryCodes.trinidadAndTobago: 'TT',
  WeatherCountryCodes.tunisia: 'TN',
  WeatherCountryCodes.turkiye: 'TR',
  WeatherCountryCodes.turkmenistan: 'TM',
  WeatherCountryCodes.turksAndCaicosIslands: 'TC',
  WeatherCountryCodes.tuvalu: 'TV',
  WeatherCountryCodes.uganda: 'UG',
  WeatherCountryCodes.ukraine: 'UA',
  WeatherCountryCodes.unitedArabEmirates: 'AE',
  WeatherCountryCodes.unitedKingdomofGreatBritainandNorthernIreland: 'GB',
  WeatherCountryCodes.unitedStatesMinorOutlyingIslands: 'UM',
  WeatherCountryCodes.unitedStatesOfAmerica: 'US',
  WeatherCountryCodes.uruguay: 'UY',
  WeatherCountryCodes.uzbekistan: 'UZ',
  WeatherCountryCodes.vanuatu: 'VU',
  WeatherCountryCodes.venezuela: 'VE',
  WeatherCountryCodes.vietnam: 'VN',
  WeatherCountryCodes.virginIslandsBritish: 'VG',
  WeatherCountryCodes.virginIslandsUS: 'VI',
  WeatherCountryCodes.wallisAndFutuna: 'WF',
  WeatherCountryCodes.westernSahara: 'EH',
  WeatherCountryCodes.yemen: 'YE',
  WeatherCountryCodes.zambia: 'ZM',
  WeatherCountryCodes.zimbabwe: 'ZW',
};

/// Maps String Alpha-2 country code to their enum [WeatherCountryCodes]
Map<String, WeatherCountryCodes> weatherCountryCodesStringReversed = Map.fromEntries(weatherCountryCodesString.entries.map((e) => MapEntry(e.value, e.key)));